# Generated by Django 5.2.9 on 2025-12-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('details', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('RATE', models.IntegerField()),
            ],
        ),
    ]
