# Generated by Django 5.2.9 on 2025-12-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='manufacture_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='RATE',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='product_quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='details',
            new_name='transport_details',
        ),
    ]
