# Generated by Django 5.2.7 on 2025-11-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField()),
                ('car_name', models.CharField()),
                ('enginenum', models.IntegerField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
